import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Landing from "./landing";
import Layout from "@/components/Layout";
import { Box } from "@mui/material";
import ArrowUpwardIcon from "@mui/icons-material/ArrowUpward";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Prathamesh Chavan - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Layout>
          <Landing />
          {/* <Service />
          <Projects />
          <Exp_Edu />
          <Skills />
          <Contact /> */}
        </Layout>

        <Box sx={{
            position: "fixed",
            right: "20px",
            bottom: "20px",
            height: "60px",
            width: "60px",
            border:"3px solid #8750f7",
            display:"flex",
            justifyContent:"center",
            alignItems:"center",
            borderRadius:"50%",
            cursor:"pointer",
            color:"#8750f7"
          }}>
          <ArrowUpwardIcon />
        </Box>
        
        <Script src="https://unpkg.com/aos@next/dist/aos.js" strategy="afterInteractive" onLoad={() => {
            AOS.init();
        }} />
      </main>
    </>
  );
}
