import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Landing from "./landing";
import Service from "./service";
import Projects from "./projects";
import Exp_Edu from "./exp_edu";
import Skills from "./skills";
import Contact from "./contact";
import Layout from "@/components/Layout";
import { Box, IconButton } from "@mui/material";
import ArrowUpwardIcon from "@mui/icons-material/ArrowUpward";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Prathamesh Chavan - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Layout>
          <Landing />
          {/* <Service />
          <Projects />
          <Exp_Edu />
          <Skills />
          <Contact /> */}
        </Layout>
        {/* <IconButton
          style={{
            position: "fixed",
            right: "20px",
            bottom: "20px",
            height: "60px",
            width: "50px",
          }}
          className="outlined-btn"
        >

          <ArrowUpwardIcon />
        </IconButton> */}

        <Box sx={{
            position: "fixed",
            right: "20px",
            bottom: "20px",
            height: "60px",
            width: "60px",
            border:"3px solid #8750f7",
            display:"flex",
            justifyContent:"center",
            alignItems:"center",
            borderRadius:"50%",
            cursor:"pointer",
            color:"#8750f7"
          }}>
        <ArrowUpwardIcon />

        </Box>
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>AOS.init();</script>
      </main>
    </>
  );
}
